name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black flake8 mypy pytest pytest-cov

      - name: Run tests
        run: |
          pytest

      - name: Check code formatting with Black
        run: |
          black --check .

      - name: Lint with flake8
        run: |
          flake8 .

      - name: Type check with mypy
        run: |
          mypy game_classes.py main.py
